baseurl = "**Your site is ready to be published at https://tobayash.github.io/tomokobablog/**"
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"
title = "tomokoba website"
theme = "hugo-theme-yinyang"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[[params.socials]]
name = "Main page"
link = "https://tobayash.github.io/hp2/index.html"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/tomokoba10"

