baseurl = "**Your site is ready to be published at https://tobayash.github.io/tomokobablog/**"
relativeurls = true
publishDir = "docs"
hasCJKLanguage = true
languageCode = "ja-jp"
title = "tomokoba website"
theme = "hugo-theme-yinyang"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"


[params]
headTitle = "Tomokoba blog"
extraHead = ''
[[params.socials]]
name = "Main page"
link = "https://tobayash.github.io/hp2/index.html"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/tomokoba10"

