---
title: "COVID-19対応者ガイドの紹介資料まとめ"
author: "tomokoba"
date: '2020-08-07'
categories: ["COVID-19"]
tags: ["COVID-19", "IASC","WHO"]
---

<meta charset="utf-8" />

<style>
  @import url(https://fonts.googleapis.com/earlyaccess/notosansjapanese.css);
  @import url(https://fonts.googleapis.com/css?family=Lato:400,900);
  body {
  <!-- font-size: 100%; -->
  }
</style>
<!-- Loading mathjax macro -->
<!-- Load mathjax -->
<script src="https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML"></script>
<!-- MathJax configuration -->
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
        tex2jax: {
            inlineMath: [ ['$','$'], ["\\(","\\)"] ],
            displayMath: [ ['$$','$$'], ["\\[","\\]"] ],
            processEscapes: true,
            processEnvironments: true
        },
        // Center justify equations in code and markdown cells. Elsewhere
        // we use CSS to left justify single line equations in code cells.
        displayAlign: 'center',
        "HTML-CSS": {
            styles: {'.MathJax_Display': {"margin": 0}},
            linebreaks: { automatic: true }
        }
    });
</script>
<!-- End of mathjax configuration -->

## COVID-19対応者ガイド
新型コロナウイルス感染症（COVID-19）の流行拡大により、医療、経済、流通など、社会の様々な側面において問題が発生している。それらの問題に対応する人々（対応者、レスポンダー）は、自らも家族とともにコロナ禍で生活していながら、社会からの様々な要請に応えなければならない。<br>
WHOやUNICEFなどの人道支援関連機関からなる機関間常設委員会（Inter-Agency Standing Committee：IASC）は、2020年5月26日にCOVID-19対応者のための心理社会的スキルに関するガイドラインを作成した。このガイドラインは、対応者自身のセルフケア、思いやりのあるコミュニケーション、実用的な支援、ストレスマネジメント、社会的弱者について、イラスト付きでわかりやすく解説し、具体的な手法や材料も提供してくれるものである。<br>
日本語訳は2020年8月に作成され、以下のIASCのホームページから手に入れることができる。<br>
https://interagencystandingcommittee.org/iasc-reference-group-mental-health-and-psychosocial-support-emergency-settings/iasc-guidance-basic

### ガイドで紹介された資料について
ガイドラインにはその他の資料が紹介されている。そのいくつかは日本語に訳されているものもあるが、いくつかはない。<br>
それぞれの資料については、以下の通り、Twitter（@tomokoba10）で要約を紹介してきました（日本語訳があるものはそのリンク）。<br>
※なお、Twitter上では"#COVID19レスポンダーガイド"でまとめています。

#### p.5
1. IASC(2020)...: https://twitter.com/tomokoba10/status/1290501476830212097?s=20
2. WHO(2020)...: https://twitter.com/tomokoba10/status/1279222330053427201?s=20
3. WHO(2012)...: なし
<br>
<br>

#### p.8 その他のセルフケアとチームケアの資料
##### 心理的応急処置（PFA）
+ フィールドワーカーのためのPFAガイド（WHO, WTF and WVI, 2011）: https://twitter.com/tomokoba10/status/1290509675146825728?s=20
+ COVID-19アウトブレイク中の遠隔PFA暫定ガイダンス（IFRC心理社会的支援のためのリファレンスセンター）: https://twitter.com/tomokoba10/status/1276267786784796672?s=20
    
##### 新型コロナウイルス感染症のストレスの対処に関する1ページ資料（WHO）
+ 読みやすいインフォグラフィック: https://twitter.com/tomokoba10/status/1290502237190410240?s=20
    
##### 14日間のウェルビーイング日記
+ 自分自身の対処法を立てるための対話型クリエイティブカレンダー: https://twitter.com/tomokoba10/status/1275822726234554370?s=20
    
##### 新型コロナウイルスに関連する社会的スティグマ
+ 社会的スティグマの防止と対策のためのガイド: https://twitter.com/tomokoba10/status/1276126562253860869?s=20
    
##### ストレスの高い時期にどんなことをすべきか：イラスト入りガイド（WHO）
+ ストレス管理を助ける情報とスキルが書かれた、読みやすいイラスト入りのガイド: https://twitter.com/tomokoba10/status/1290533827614400513?s=20
<br>
<br>

#### p.18 女性や女児への新型コロナウイルス感染症の影響
+ 国連女性機関 UN Women による政策提言：新型コロナウイルス感染症の女性への影響: https://twitter.com/tomokoba10/status/1276137922308128769?s=20
+ 新型コロナウイルス感染症の対応における性的搾取や虐待からの保護（PSEA）に関するIASC暫定テクニカルノート: https://twitter.com/tomokoba10/status/1276858282846511104?s=20
+ 暫定ガイダンス：新型コロナウイルス感染症の流行時のジェンダーに対する警告: https://twitter.com/tomokoba10/status/1280794517562462209?s=20
<br>
<br>

#### p.18 悲しみの中にいる人たちへのサポート
+ 普段と異なる状況の中で悲しむこと（アイルランドホスピス財団）: https://twitter.com/tomokoba10/status/1277270612306587651?s=20
+ 子どもたちと死について話し、子どもたちの悲しみへの対処を助けるために: https://twitter.com/tomokoba10/status/1281231075331633153?s=20
<br>
<br>

#### p.19 難民キャンプや非公式の難民・移民環境で生活する人たちへのサポート
+ 新型コロナウイルス感染症と移民、難民、虐待などで保護された子どもたちに関するクイック・ヒント（ユニセフ）: https://twitter.com/tomokoba10/status/1278975859181801472?s=20
<br>
<br>

#### p.19 障害のある人たちへのサポート
+ 障害のある人たちを社会に受け入れるための新型コロナウイルス感染症の対応に向けて：国際障害者同盟からの10の提言: https://twitter.com/tomokoba10/status/1278355353109848064?s=20
+ 障害者インクルーシブ・コミュニティ・アクション：新型コロナウイルス感染症マトリックス（CBM）: https://twitter.com/tomokoba10/status/1282595350969081856?s=20
<br>
<br>

#### p.20 スタッフやボランティアをサポートする管理者・上司へのアドバイス
+ 感染流行時にレジリエンスを維持するために（ヘディングトン研究所）: <br>

|　    | 要約ツイート      |
|:-----------|:------------:|
|人道的支援者に特有の困難     |https://twitter.com/tomokoba10/status/1291312333881393154?s=20|
|最悪の状況ですると良いこと  |https://twitter.com/tomokoba10/status/1291312069917028354?s=20|
|人道的な地域社会で今できること      |https://twitter.com/tomokoba10/status/1291311680073285632?s=20|
| 道徳的負傷     |https://twitter.com/tomokoba10/status/1291001989753536512?s=20|
|パンデミック中に感情を管理する方法    |https://twitter.com/tomokoba10/status/1285215527770550272?s=20|
| パンデミック中のリーダーがする5つのこと      |https://twitter.com/tomokoba10/status/1282926032513691649?s=20|
|リスクの伝播効果      |https://twitter.com/tomokoba10/status/1284135620533612545?s=20|



+ 管理者とスタッフのための組織的なスタッフケア資源（アンタレス財団）: https://twitter.com/tomokoba10/status/1283780130926497794?s=20
+ 新型コロナウイルス流行時のスタッフ、ボランティア、コミュニティのためのメンタルヘルスとこころのケア（IFRC:国際赤十字赤新月社連盟）: https://twitter.com/tomokoba10/status/1283354014998949888?s=20
<br>
<br>
